// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqxynihttysspiqvwmlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xeHluaWh0dHlzc3BpcXZ3bWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3MjQyODEsImV4cCI6MjA0OTMwMDI4MX0.QOU7zl1paDyWRPf9OHAoZCo2CIkGyN_EL3XTWP7GLVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});